backend:
  name: github
  repo: Ash1eyC0des/b-r-computers-blog
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: image, label: Image, widget: image, allow_multiple: false }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: categories, label: Categories, widget: select, multiple: true, options: ['Computer', 'Micro Chip Repair', 'Technology', 'iPhone', 'Replace'] }
      - { name: author, label: Author }